### ISSUE TITLE
Problem with a struct built with the NativeCall

### ISSUE THREAD

**Issue by mrhdias** [jnthn/zavolaj#21]
Hi,

I have a problem with a struct built with the NativeCall module. When I run the script below it returns the wrong values​​.
$ ./test.p6
Alpha: 429496729855 (Should returns 255)
Red: 858993459350 (Should returns 100)
Green: 44436640 (Should returns 150)
Blue: 139740294669976 (Should returns 200)

I need to extract the values ​​stored in a C struct from the Imlib2 library.
Someone can help me find a solution to fix this problem?
Thanks

test.c

    #include <stdio.h>
    #include <stdlib.h>
    #include <string.h>

    struct _lib_color {
        int alpha, red, green, blue;
    };

    typedef struct _lib_color lib_Color;

    lib_Color *lib_get_colors(void) {
        lib_Color *obj = (lib_Color *) malloc(sizeof(lib_Color));
        obj->alpha = 255;
        obj->red = 100;
        obj->green = 150;
        obj->blue = 200;

        return obj;
     }

test.p6

    #!/usr/bin/env perl6

    use NativeCall;
    constant LIB = './test.so';

    class Imlib2::ImlibColor is repr('CStruct') {
        has int $.alpha;
        has int $.red;
        has int $.green;
        has int $.blue;

        method alpha() { return $!alpha; }
        method red() { return $!red; }
        method green() { return $!green; }
        method blue() { return $!blue; }
    }
    sub lib_get_colors() returns Imlib2::ImlibColor is native(LIB) { ... }
    my $colors = lib_get_colors();
    say "Alpha: " ~ $colors.alpha ~ " (Should returns 255)";
    say "Red: " ~ $colors.red ~ " (Should returns 100)";
    say "Green: " ~ $colors.green ~ " (Should returns 150)";
    say "Blue: " ~ $colors.blue ~ " (Should returns 200)";
    exit();

$ cc -o test.o -fPIC -c test.c
$ cc -shared -s -o test.so test.o
$ rm test.o

**Comment by FROGGS** [comment]
This is fixed now, and requires latest rakudo and latest NativeCall.
