### ISSUE TITLE
issues on x86

### ISSUE THREAD

**Issue by FROGGS** [jnthn/zavolaj#37]
There are failing tests on x86 (linux in this case):
```perl
t/01-argless.t ......... ok   
t/02-simple-args.t ..... ok     
t/03-simple-returns.t .. ok   
t/04-pointers.t ........ ok   
t/05-arrays.t .......... Failed 3/26 subtests 
t/06-struct.t .......... Failed 25/30 subtests 
t/07-writebarrier.t .... ok   
t/08-callbacks.t ....... Failed 1/9 subtests 

Test Summary Report
-------------------
t/05-arrays.t        (Wstat: 0 Tests: 26 Failed: 3)
  Failed tests:  10-12
t/06-struct.t        (Wstat: 139 Tests: 9 Failed: 4)
  Failed tests:  6-9
  Non-zero wait status: 139
  Parse errors: Bad plan.  You planned 30 tests but ran 9.
t/08-callbacks.t     (Wstat: 0 Tests: 9 Failed: 1)
  Failed test:  5
Files=8, Tests=73, 10 wallclock secs ( 0.06 usr  0.02 sys +  8.23 cusr  0.42 csys =  8.73 CPU)
Result: FAIL
```

Valgrind output: https://gist.github.com/FROGGS/41375617155044651cdf
There is also a windows-only hack: https://github.com/jnthn/zavolaj/commit/20e50dabaeff42dfe0b49ddd87608cd55d71e082

The problem is the struct in e.g. 05-array.c, which has an 32bit element, but we're trying to read 64bit because `int` in rakudo seems to be about 64bit even on 32bit platforms. (Changing the `int` in the class in 05-array.t to `int32` makes it work.)

What would be the fix? Treating `int` in Perl 6 as `int32` or `int64` depending on the platform?

**Comment by b2gills** [comment]
This is a problem because `int` is currently the same as the largest native integer. Which means on 32-bit x86 architectures all the way back to the [80386](https://en.wikipedia.org/wiki/Intel_80386), [`int` is the same as `int64`](https://en.wikipedia.org/wiki/Intel_80386#Datatypes_of_80386).

So `int` is currently attempting to fill two roles, maximal integer, and platform size.

**Comment by FROGGS** [comment]
As I said on the irc channel yesterday you have to keep in mind, that a Perl 6 `int` is about a C `long`. And a C `long` is either 32bit or 64bit wide depending on you machine. A C `int` is always 32bit wide.

We need to keep the terms straight. So when we talk about `int` just like that, we mean Perl 6.

**Comment by FROGGS** [comment]
Ahh, and also, we are talking about C vs Perl 6 terms, so think shows nicely our problem:
http://en.wikipedia.org/wiki/C_data_types

`int` is specified to be *at least* 32bit wide, and `long` is specified to be *at least* 64bit wide. So in a distant future we have to care about a variable sized `long` as well.

**Comment by arnsholt** [comment]
The problem isn't really that int is trying to fill two roles, but more that we (the people who made NativeCall) have shanghaied it into playing two roles. =)

The Perl 6 `int` type is supposed to be more or less "whatever the underlying VM thinks is a sensible integer type" (at least that's my understanding of it). In practice this means 64 bits as all of our VMs ATM consider that to be "sensible" (`int64_t` on Parrot and Moar, `long` on JVM).

My current idea for fixing this is adding two new types to Rakudo, `cint` and `clong`. Implementing this will require extending the P6int REPRs in NQP (for Parrot and JVM) and Moar with a new feature ("your as many bits wide as this C type") and some plumbing in Rakudo to signal this to the REPR. I've started hacking on this, but haven't had the time to actually finish it.

**Comment by FROGGS** [comment]
We don't need a `cint` when we can have a `long` at Perl 6 level...

`cint` is not needed because an `int` in C is always 32bits wide. We have a `int32` for that purpose.
A Perl 6 level `long` would then match a `long` in C and would be variable in size. But that's only slightly better than the situation we have now, because wo just change names.

So, I am in favour of adding a `long` type to match C semantics.

**Comment by muraiki** [comment]
I experienced similar but different failures on a 32-bit FreeBSD machine. The FreeBSD version is unfortunately a bit old (7.3-RELEASE-p2) but I did successfully build perl6 2015.01-44-g166cd3c with MoarVM version 2015.01-6-g89ddb76.

```
t/01-argless.t ......... ok
t/02-simple-args.t ..... ok
t/03-simple-returns.t .. ok
t/04-pointers.t ........ ok
# Failed test 'int in struct in element 0'
# at t/05-arrays.t line 50
# expected: '2'
#      got: '12884901890'
# Failed test 'int in struct in element 1'
# at t/05-arrays.t line 50
# expected: '3'
#      got: '21474836483'
Unknown type 'vmarray' used for native call
  in method postcircumfix:<( )> at lib/NativeCall.pm6:139
  in block <unit> at t/05-arrays.t:101
# Looks like you planned 20 tests, but ran 16
# Looks like you failed 2 tests of 16
t/05-arrays.t .......... 
Dubious, test returned 2 (wstat 512, 0x200)
Failed 6/20 subtests 
# Failed test 'getting int from C-created struct'
# at t/06-struct.t line 1
# expected: '17'
#      got: '-3689348813882916847'
# Failed test 'getting num from C-created struct'
# at t/06-struct.t line 1
# expected: 4.2
# got:      2.81169881985422e-313
# Failed test 'getting int8 from C-created struct'
# at t/06-struct.t line 1
# expected: '13'
#      got: '-61'
# Failed test 'getting num32 from C-created struct'                                                         [57/266]
# at t/06-struct.t line 1
# expected: -6.28
# got:      9.90758863839147e-12
use of uninitialized value $got of type Any in string context  in sub is at lib/Test.pm:113
# Failed test 'C-created array member, elem 1'
# at t/06-struct.t line 121
# expected: '2'
use of uninitialized value $got of type Any in string context  in sub is at lib/Test.pm:117
#      got: ''
use of uninitialized value $got of type Any in string context  in sub is at lib/Test.pm:113
# Failed test 'C-created array member, elem 2'
# at t/06-struct.t line 1
# expected: '3'
use of uninitialized value $got of type Any in string context  in sub is at lib/Test.pm:117
#      got: ''
use of uninitialized value $got of type Any in string context  in sub is at lib/Test.pm:113
# Failed test 'C-created array member, elem 3'
# at t/06-struct.t line 1
# expected: '5'
use of uninitialized value $got of type Any in string context  in sub is at lib/Test.pm:117
#      got: ''
# Failed test 'field 1 from struct 1 in struct'
# at t/06-struct.t line 1
# expected: '7'
#      got: '47244640263'
# Failed test 'field 2 from struct 1 in struct'
# at t/06-struct.t line 1
# expected: '11'
#      got: '679560296'
t/06-struct.t .......... 
Failed 9/19 subtests 
t/07-writebarrier.t .... ok
# Failed test 'struct callback int argument'
# at t/08-callbacks.t line 43
# expected: '-42'
#      got: '72340172821233622'
# Looks like you failed 1 tests of 5
t/08-callbacks.t ....... 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/5 subtests 
t/09-nativecast.t ...... ok
t/10-cglobals.t ........ ok
Test Summary Report
-------------------
t/05-arrays.t        (Wstat: 512 Tests: 16 Failed: 2)
  Failed tests:  10-11
  Non-zero exit status: 2
  Parse errors: Bad plan.  You planned 20 tests but ran 16.
t/06-struct.t        (Wstat: 139 Tests: 19 Failed: 9)
  Failed tests:  6-14
  Non-zero wait status: 139
t/08-callbacks.t     (Wstat: 256 Tests: 5 Failed: 1)
  Failed test:  5
  Non-zero exit status: 1
Files=10, Tests=94, 24 wallclock secs ( 0.06 usr  0.16 sys + 11.66 cusr  7.79 csys = 19.67 CPU)
Result: FAIL
```

**Comment by arnsholt** [comment]
That's interesting. Is this an x86 machine, or some other architecture?

**Comment by muraiki** [comment]
i386

**Comment by FROGGS** [comment]
@muraiki The error message `Unknown type 'vmarray' used for native call` means that your rakudo (and nqp + moarvm) is too old for this version of NativeCall.

So this error should go away when you upgrade your installation, though the other errors probably persist.

**Comment by muraiki** [comment]
Ok, using perl6 version 2015.01-132-ge2b01fe built on MoarVM version 2015.01-34-g2d7eddb I get the same tests that fail, although one of the test results changed. But yeah, it seems to be the same basic problem as in the OP. Sorry for not updating first!

```
# Failed test 'getting num32 from C-created struct'
# at t/06-struct.t line 1
# expected: -6.28
# got:      1.45281842112155e-11
```

**Comment by FROGGS** [comment]
That improves the situation: https://github.com/MoarVM/MoarVM/commit/728a748bd7

```bash
froggs@ubuntu-x86:~/dev/zavolaj$ PERL6LIB=lib prove -e perl6-m t/*.t
t/01-argless.t ......... ok   
t/02-simple-args.t ..... ok     
t/03-simple-returns.t .. ok   
t/04-pointers.t ........ ok     
t/05-arrays.t .......... ok     
t/06-struct.t .......... 1/19 
# Failed test 'C-created array member, elem 1'
# at t/06-struct.t line 121
# expected: '2'
#      got: '12884901890'

# Failed test 'C-created array member, elem 2'
# at t/06-struct.t line 122
# expected: '3'
#      got: '210453397509'

# Failed test 'C-created array member, elem 3'
# at t/06-struct.t line 123
# expected: '5'
#      got: '34579217904'
t/06-struct.t .......... 13/19 # Looks like you failed 3 tests of 19
t/06-struct.t .......... Dubious, test returned 3 (wstat 768, 0x300)
Failed 3/19 subtests 
t/07-writebarrier.t .... ok   
t/08-callbacks.t ....... ok   
t/09-nativecast.t ...... ok   
t/10-cglobals.t ........ ok   

Test Summary Report
-------------------
t/06-struct.t        (Wstat: 768 Tests: 19 Failed: 3)
  Failed tests:  10-12
  Non-zero exit status: 3
Files=10, Tests=98, 29 wallclock secs ( 0.06 usr  0.02 sys + 28.43 cusr  0.71 csys = 29.22 CPU)
Result: FAIL
```

**Comment by FROGGS** [comment]
NativeCall passes now on x86 and x86_64 machines with the 'longer' branches of MoarVM, nqp, rakudo and NativeCall:

```shell
froggs@linux:~/dev/zavolaj$ PERL6LIB=lib prove -e perl6-m t/*.t
t/01-argless.t ......... ok   
t/02-simple-args.t ..... ok     
t/03-simple-returns.t .. ok   
t/04-pointers.t ........ ok     
t/05-arrays.t .......... ok     
t/06-struct.t .......... ok     
t/07-writebarrier.t .... ok   
t/08-callbacks.t ....... ok   
t/09-nativecast.t ...... ok   
t/10-cglobals.t ........ ok   
All tests successful.
Files=10, Tests=98, 22 wallclock secs ( 0.07 usr  0.01 sys + 20.70 cusr  0.86 csys = 21.64 CPU)
Result: PASS
```

```shell
froggs@ubuntu-x86:~/dev/zavolaj$ PERL6LIB=lib prove -e perl6-m t/*.t
t/01-argless.t ......... ok   
t/02-simple-args.t ..... ok     
t/03-simple-returns.t .. ok   
t/04-pointers.t ........ ok     
t/05-arrays.t .......... ok     
t/06-struct.t .......... ok     
t/07-writebarrier.t .... ok   
t/08-callbacks.t ....... ok   
t/09-nativecast.t ...... ok   
t/10-cglobals.t ........ ok   
All tests successful.
Files=10, Tests=98, 27 wallclock secs ( 0.07 usr  0.01 sys + 25.26 cusr  0.63 csys = 25.97 CPU)
Result: PASS
```
Please test!

**Comment by muraiki** [comment]
All tests pass. Thanks!

**Comment by FROGGS** [comment]
\o/

**Comment by FROGGS** [comment]
This is resolved now on all backends. NativeCall will be moved to the rakudo repository soonish, to solve the problem that the rakudo and NativeCall revisions have to fit.
