### ISSUE TITLE
ability to nativecast a CStruct to another

### ISSUE THREAD

**Issue by timo** [jnthn/zavolaj#49]
I need this for SDL2. Otherwise i'd have to do an ugly workaround, like having a CPointer that i initialize to point at the memory location of the CStruct or something like that ...

**Comment by FROGGS** [comment]
You solved that issue the day you opened this issue: https://github.com/MoarVM/MoarVM/commit/d481136a0e64945dd9f52a8949e32bf6f7c5a297
