### ISSUE TITLE
===SORRY!=== Error while compiling lib/NativeCall.pm6

### ISSUE THREAD

**Issue by cschwenz** [jnthn/zavolaj#57]
==> Building NativeCall
    Compiling lib/NativeCall.pm6 to mbc
    ===SORRY!=== Error while compiling lib/NativeCall.pm6
    'long' cannot inherit from 'ctype' because it is unknown.
    at lib/NativeCall.pm6:68
    ------> 
    build stage failed for NativeCall: Failed building lib/NativeCall.pm6

This is with the 2015.01 version of Rakudo (build exclusively for the MoarVM).

**Comment by vendethiel** [comment]
Right... NativeCall has been moved into rakudo core, and you need a previous version of nativecall to get it to work with rakudo 2015.01 I guess

**Comment by cschwenz** [comment]
As the only reason I was attempting to compile NativeCall was to then install Inline::* (which declares NativeCall as a prerequisite), should I fix Inline to not have NativeCall as a prerequisite?

**Comment by moritz** [comment]
yes, it's not necessary anymore

**Comment by FROGGS** [comment]
This is resolved now.
