### ISSUE TITLE
c2ffi project looks useful, maybe there should be something similar to c2ffi-ruby for Perl 6

### ISSUE THREAD

**Issue by xaduha** [jnthn/zavolaj#61]
https://github.com/rpav/c2ffi

https://github.com/rpav/c2ffi-ruby

**Comment by FROGGS** [comment]
We've got this [^1] which uses gcc but seems equally awesome.
And I can image that it would be possible to add a clang backend too...

[^1] https://github.com/Skarsnik/gptrixie

@Skarsnik: c2nativecall would also be a good name ;o)
